language: php

sudo: false

addons:
  postgresql: "9.6"
  apt:
    packages:
      - oracle-java9-installer
      - oracle-java9-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.0
 - 7.2

env:
 global:
  - MOODLE_BRANCH=MOODLE_37_STABLE
 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install node
  - cd ../../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat